name: Pull Requests
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Action
      uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        curl -sSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash
        curl -sL "https://keybase.io/crystal/pgp_keys.asc" | sudo apt-key add -Y -
        echo "deb https://dist.crystal-lang.org/apt crystal main" | sudo tee /etc/apt/sources.list.d/crystal.list
        sudo apt update
        sudo apt install -y build-essential crystal libssl-dev libxml2-dev libyaml-dev libgmp-dev libreadline-dev libz-dev
        shards install --verbose
    - name: Run Test Suite
      run: |
        shards build --verbose
        crystal tool format --check
        crystal spec --verbose