name: Nightly

on: [pull_request]
  # push:
  #   branches:
  #   - main
  # schedule:
  #   - cron: 0 1 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        shards install --verbose
    - name: Run Test Suite
      run: |
        crystal tool format --check
        crystal spec --verbose --error-trace --time -Dpreview_mt
        crystal run --verbose --error-trace --stats -Dpreview_mt ./try.cr
  coverage:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v2
    - uses: codecov/codecov-action@v2
      with:
        directory: ./.github/coverage
