name: Nightly

on:
  push:
    branches:
    - main
  schedule:
    - cron: 0 1 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        shards install --verbose
        crystal build .github/run_coverage.cr -D skip-integrations -o .github/run_coverage
    - name: Run Test Suite
      run: |
        crystal tool format --check
        crystal spec --verbose --error-trace --time -Dpreview_mt
    - uses: codecov/codecov-action@v2
      with:
        directory: ./.github/coverage
