name: Nightly
on: [pull_request]
# on:
#   push:
#     branches:
#     - main
#   schedule:
#     - cron: 0 1 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        shards install --verbose
    - name: Run Test Suite
      run: |
        crystal tool format --check
        crystal spec --verbose --error-trace --time -Dpreview_mt
        crystal run --verbose --error-trace --stats -Dpreview_mt ./try.cr
  coverage:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update -y
        apt install -y kcov
        shards install --verbose
    - name: Code Coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        crystal build ./run_tests.cr -D skip-integrations
        kcov --clean --include-path=./src ./coverage ./run_tests
        bash <(curl -s https://codecov.io/bash) -s ./coverage
