name: Nightly
on:
  push:
    branches:
    - master
  schedule:
    - cron: 0 1 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: shards install --verbose
    - name: Run Test Suite
      run: |
        shards build --verbose
        crystal tool format --check
        crystal spec --verbose
