name: Nightly
on: [pull_request]
# on:
#   push:
#     branches:
#     - main
#   schedule:
#     - cron: 0 1 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        shards install --verbose
    - name: Run Test Suite
      run: |
        crystal tool format --check
        crystal spec --verbose --error-trace --time -Dpreview_mt
        crystal run --verbose --error-trace --stats -Dpreview_mt ./try.cr
  coverage:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        apt update -y
        apt install -y sudo curl gnupg ca-certificates apt-transport-https
        sudo ln -snf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime
        echo Europe/Amsterdam > /etc/timezone
        curl -fsSL https://crystal-lang.org/install.sh | sudo bash
        sudo apt update -y
        sudo apt full-upgrade -y
        shards install --verbose
        crystal build ./run_tests.cr -D skip-integrations
        crystal run --verbose --error-trace --stats -Dpreview_mt ./run_tests.cr
    - name: Code Coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        sudo apt install -y kcov
        sudo kcov --clean --include-path=./src ./coverage ./run_tests
        bash <(curl -s https://codecov.io/bash) -s ./coverage
