name: Spec

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    container:
      image: crystallang/crystal
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, macos-12]
    steps:
    - name: MacOs Dependencies
      run: |
        brew install --verbose docker
      if: startsWith(matrix.os, 'macOS')
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        shards install --verbose
        crystal build .github/run_coverage.cr -o .github/run_coverage
    - name: Run Test Suite
      run: |
        crystal tool format --check
        crystal spec --verbose --error-trace --time
    - uses: codecov/codecov-action@v2
      with:
        directory: ./.github/coverage
